// AUTO-GENERATED by sync-reviews-config.py — do not edit by hand.
// Source of truth: /Documents/Agent 51/.env.shared (AHP_PLACES_API_KEY / AHP_PLACES_ID)
window.AHP_REVIEWS_CONFIG = window.AHP_REVIEWS_CONFIG || {};
window.AHP_REVIEWS_CONFIG.apiKey = "AIzaSyB-PzaucCV56a9IlH9dcQxu1zhheGPHDlo";
window.AHP_REVIEWS_CONFIG.placeId = "ChIJVX9WfxxW64wRPKn0jyvxf_I";
